# Don't print a new line at the start of the prompt 
add_newline = false

format = """
$directory$git_branch$git_status$git_commit
$cmd_duration$status$character
"""

[directory]
format = '[$path]($style)[$read_only]($read_only_style) '
read_only = " [ read only]"
read_only_style = "bold yellow"
style = "blue bold"
truncation_length = 3
truncate_to_repo = false
truncation_symbol = ".../"

[git_status]
staged = '[+](bold green)'
untracked = '[?](bold blue)'
deleted = '[✘](bold red)'
ahead = '[⇡](bold red)'
behind = '[⇣](bold red)'
diverged = '[⇕](bold red)'
renamed = '[»](bold red)'
conflicted = '[=](bold red)'
format = '([\[$all_status$ahead_behind\]]($style)) '
style = "bold red"

[git_commit]
commit_hash_length = 4

[python]
symbol = " "
scan_for_pyfiles = true

[dart]
symbol = " "

[docker]
symbol = " "

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "

[hg_branch]
symbol = " "

[java]
symbol = " "

[memory_usage]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "
disabled = true

[php]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[cmd_duration]
min_time = 500
format = "took [$duration ](bold yellow)"

[status]
format = '[\[$int\]]($style)'
style = 'bg:red bold'
map_symbol = false
disabled = false

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[->](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[ ->](bold red)"


[time]
disabled = false
style = "bold yellow"
format = '@[$time]($style)'
time_format = "%H:%M"

[hostname]
ssh_only = false
format = "[$hostname]($style)"
style = "bold dimmed green"

[line_break]
disabled = false

[username]
show_always = true
format = "[$user]($style)@"
style_user = "bold yellow"









