# Print a new line at the start of the prompt 
add_newline = true

format = """$all
"""

[directory]
format = '[$path]($style)[$read_only]($read_only_style) '
read_only = " "
read_only_style = "bold yellow"
style = "cyan bold"
truncation_length = 3
truncate_to_repo = true
truncation_symbol = ''



[git_status]

# This settings look like:
# .dotfiles on  master [!(3)]

staged = '[+\([$count](bold green)\)](bold green)' 
untracked = '[?\([$count](bold blue)\)](bold blue)'
modified = '[!\([$count](bold cyan)\)](bold cyan)'
deleted = '[✘\([$count](bold red)\)](bold red)'
ahead = '[⇡\([$count](bold red)\)](bold red)'
behind = '[⇣\([$count](bold red)\)](bold red)'
diverged = '[⇕\([$count](bold red)\)](bold red)'
renamed = '[»\([$count](bold yellow)\)](bold yellow)'
conflicted = '[≠\([$count](bold red)\)](bold red)'
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold red"

[git_commit]
commit_hash_length = 4


[cmd_duration]
min_time = 500
format = "[took](bold white) [$duration ](bold yellow)"

[status]
format = '[\[$int\]]($style)'
style = 'bg:red bold'
map_symbol = false
disabled = false

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[❯](green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[ ❯](red)"


[time]
disabled = true
style = "bold blue"
format = '@[$time]($style) '
time_format = "%H:%M"
use_12hr = true

[hostname]
ssh_only = true
format = "[$hostname]($style) "
style = "bold cyan"

[line_break]
disabled = false

[username]
show_always = false
format = "as [$user]($style) in "
style_user = "bold yellow"









